<a href="https://colab.research.google.com/github/Fpadilla1970/PyTorch_learning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import numpy as np

In [4]:
my_list = [[1,2,3,4],[6,7,8,9]]
print(my_list)

[[1, 2, 3, 4], [6, 7, 8, 9]]


In [11]:
np1= np.random.rand(3,4)
np1

array([[0.72273484, 0.47558066, 0.34756185, 0.45106496],
       [0.1405165 , 0.53826809, 0.71991451, 0.33474063],
       [0.41460949, 0.36811302, 0.08499355, 0.33172756]])

In [9]:
tensor_2d= torch.randn(3,4)
tensor_2d

tensor([[ 0.1894,  0.0879,  0.7972, -0.9962],
        [ 0.0316,  0.3937, -1.2094, -0.1926],
        [ 0.7147, -0.2303, -0.5430, -0.8422]])

In [9]:
tensor_3d= torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#create tensor from numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7227, 0.4756, 0.3476, 0.4511],
        [0.1405, 0.5383, 0.7199, 0.3347],
        [0.4146, 0.3681, 0.0850, 0.3317]], dtype=torch.float64)

In [16]:
my_torch_4 = torch.arange(10)
my_torch_4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Reshape and View
my_torch_4.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
# Reshape without knowing
my_torch_5 = torch.arange(10)
my_torch_5 = my_torch_5.reshape(2,-1)
my_torch_5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
my_torch_6 = torch.arange(10)
my_torch_7 = my_torch_6.view(2,5)
my_torch_7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
#slices
my_torch_8 = torch.arange(10)
my_torch_8= my_torch_8.reshape(5,2)
my_torch_8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [31]:
my_torch_8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])